### ISSUE TITLE
The redirect action in coreruleset is not supported in coraza WAF

### ISSUE THREAD

**Issue by sky9090** [jptosso/coraza-waf#144]
Hi,

I did some tests on the settings in the coreruleset/crs-setup.conf.example file and included this file in the Coraza-Server config.yml file, and found that the coreruleset redirect action is not support in coraza WAF. Please have a took and give me some advice.
- coraza-server config.yml
```
log_level: debug
agents:
  -
    transactions_active_limit: 100000
    transaction_ttl: 3
    bind: 0.0.0.0:9000
    protocol: spoa
    include:
      - ./docs/coraza.conf-recommended
      - ./coreruleset/crs-setup.conf.example
      - ./coreruleset/rules/*.conf
```
- coraza.conf-recommended
```
SecRuleEngine On
SecRequestBodyAccess On

SecAuditEngine On
SecAuditLogType Serial
SecAuditLog /var/log/nginx/modsec_audit.log
SecAuditLogParts BCFGHIJK
```
- Case: the coreruleset redirect action is not support in coraza WAF
    - set coreruleset/crs-setup.conf.example
      ```
      SecDefaultAction "phase:1,log,auditlog,redirect:'http://%{request_headers.host}/',tag:'Host: %{request_headers.host}'"
      SecDefaultAction "phase:2,log,auditlog,redirect:'http://%{request_headers.host}/',tag:'Host: %{request_headers.host}'"
      
      SecCollectionTimeout 600

      SecAction \
          "id:900990,\
          phase:1,\
          nolog,\
          pass,\
          t:none,\
          setvar:tx.crs_setup_version=340"
      ```
    - execute config.yml
      ```
      # go run cmd/coraza-server/main.go -f config.yml
      INFO[0000] Initializing waf                             
      FATA[0000] Failed to compile rule (invalid action "redirect"): id:900990,phase:1,nolog,pass,t:none,setvar:tx.crs_setup_version=340 
      exit status 1
      ```
